### ISSUE TITLE
%FSHARPINSTALLDIR% not set in command prompt

### ISSUE THREAD

**Issue by MichaelMay81** [aardvark-platform/template#2]
If %FSHARPINSTALLDIR% is not set, the build.cmd can't find 'fsi.exe'
> bootstrapping package manager ...
> Checking Paket version (downloading latest stable)...
> Paket.exe 5.113.1 is up to date.
> '"fsi.exe"' is not recognized as an internal or external command, operable program or batch file.

and finaly fails with:
> C:\Users\may\Documents\Dibit\Source\test\template\src\__PROJECT_NAME__\__PROJECT_NAME__.fsproj(48,3): error MSB4067: The element <#text> beneath element <ItemGroup> is unrecognized.

Workarround: use Developer Command Prompt instead

**Comment by haraldsteinlechner** [comment]
i think this was solved long time ago.... reopen if you can still reproduce
