### ISSUE TITLE
cannot run from template build

### ISSUE THREAD

**Issue by jackfoxy** [aardvark-platform/template#4]
Is there a better way to get started with Aardvark?

The template build how-to video is no longer current in how rendering is chosen https://www.youtube.com/watch?v=uFtN9J52-nw 

problems:

1) I had to manually copy nuget.exe to the .paket folder.

2) whether choosing option 0, plain rendering application or option 1, aardvark media application when I try to run

dotnet bin\Release\netcoreapp2.0\GettingStarted.dll

I get first a warning:

````
WARNING: failed: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Aardvark.Base.PixImageDevil' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'DevIL': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DevILSharp.IL.internalInit()
   at DevILSharp.IL.Init() in C:\Users\Schorsch\Desktop\buildtest\DevILSharp\src\DevILSharp\IL.fs:line 170
   at Aardvark.Base.PixImageDevil.InitDevil() in C:\Users\Schorsch\Development\aardvark.base\src\Aardvark.Base\Images\PixImageDevil.cs:line 26
   at Aardvark.Base.PixImageDevil..cctor() in C:\Users\Schorsch\Development\aardvark.base\src\Aardvark.Base\Images\PixImageDevil.cs:line 35
   --- End of inner exception stack trace ---
   at Aardvark.Base.PixImageDevil.InitDevil() in C:\Users\Schorsch\Development\aardvark.base\src\Aardvark.Base\Images\PixImageDevil.cs:line 21
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Aardvark.Base.Aardvark.LoadAll(IEnumerable`1 xs) in C:\Users\Schorsch\Development\aardvark.base\src\Aardvark.Base\Introspection\Introspection.cs:line 1032
````
   
and then throw

````
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Aardvark.Rendering.Vulkan.Instance' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Aardvark-Rendering-Vulkan>.$Platform' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'vulkan-1': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Aardvark.Rendering.Vulkan.VkRaw.vkEnumerateInstanceLayerProperties(UInt32* pPropertyCount, VkLayerProperties* pProperties)
   at <StartupCode$Aardvark-Rendering-Vulkan>.$Platform.f@36-13(UInt32* _arg1) in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.Vulkan\Core\Platform.fs:line 25
   at <StartupCode$Aardvark-Rendering-Vulkan>.$Platform..cctor() in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.Vulkan\Core\Platform.fs:line 21
   --- End of inner exception stack trace ---
   at Aardvark.Rendering.Vulkan.Instance..cctor()
   --- End of inner exception stack trace ---
   at Aardvark.Rendering.Vulkan.Instance.get_GlobalExtensions()
   at Aardvark.Application.Slim.VulkanApplication..ctor(Boolean debug, FSharpFunc`2 chooseDevice) in C:\- Data\aardvark.rendering\src\Application\Aardvark.Application.Slim.Vulkan\Application.fs:line 246
   at Program.main(String[] argv) in E:\GitRepos\GettingStarted\src\GettingStarted\Program.fs:line 14
````

**Comment by jackfoxy** [comment]
Work around is to get started with https://github.com/aardvark-platform/aardvark.docs
 instead of the template

**Comment by haraldsteinlechner** [comment]
thanks for reporting. did not recognize since i typically start from vs where output path is correct. @gsomix used runtimelibrarypath in aardvark.docs to countermeasure this https://github.com/aardvark-platform/aardvark.docs/blob/master/src/Gravity/Gravity.fsproj#L14

i can fix this later today if not fixed by then ;)

**Comment by haraldsteinlechner** [comment]
- yes, the videos are out of date, they still use net framework/mono. i'll keep this issue open till we have a new one.
- both problems have the same reason: the working directory is the wrong one. during startup we unpack native dependencies beside the assembly. if you run dotnet from project root this logic is flawed. we could do more magic regarding native dependency loading, but a more simple version is to have a proper working directory, i.e. either `cd` to the output path or use dotnetrun which internally sets working directory using `RunWorkingDirectory` as already in given in the project https://github.com/aardvark-platform/template/blob/master/src/__PROJECT_NAME__/__PROJECT_NAME__.fsproj#L14
- i updated the readme according to the necessary working directory change: https://github.com/aardvark-platform/template/commit/6c3fbd6df5da158fd0fefa0ad9a6bb6ccd044a88

**Comment by jackfoxy** [comment]
Just tried cloning again.
 
I still had to manually copy nuget.exe to .paket folder.

Built as plain rendering app with no significant warnings.
 
```dotnet run -c Release -p .\src\AardvarkTemplate\AardvarkTemplate.fsproj```
Resulted in error:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Aardvark.Rendering.Vulkan.Instance' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Aardvark-Rendering-Vulkan>.$Platform' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'vulkan-1': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Aardvark.Rendering.Vulkan.VkRaw.vkEnumerateInstanceLayerProperties(UInt32* pPropertyCount, VkLayerProperties* pProperties)
   at <StartupCode$Aardvark-Rendering-Vulkan>.$Platform.f@36-13(UInt32* _arg1) in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.Vulkan\Core\Platform.fs:line 25
   at <StartupCode$Aardvark-Rendering-Vulkan>.$Platform..cctor() in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.Vulkan\Core\Platform.fs:line 21
   --- End of inner exception stack trace ---
   at Aardvark.Rendering.Vulkan.Instance..cctor()
   --- End of inner exception stack trace ---
   at Aardvark.Rendering.Vulkan.Instance.get_GlobalExtensions()
   at Aardvark.Application.Slim.VulkanApplication..ctor(Boolean debug, FSharpFunc`2 chooseDevice) in C:\- Data\aardvark.rendering\src\Application\Aardvark.Application.Slim.Vulkan\Application.fs:line 246
   at Program.main(String[] argv) in E:\GitRepos\AardvarkTemplate\src\AardvarkTemplate\Program.fs:line 14
```
CD to the release folder and ```dotnet AardvarkTemplate.dll``` results in same error.

**Comment by gsomix** [comment]
@jackfoxy Could you please change in your `Program.fs` file line

```fsharp
use app = new VulkanApplication(true)
```

to 

```fsharp
use app = new OpenGlApplication(true)
```

and write if it works for you? Thanks!

**Comment by haraldsteinlechner** [comment]
regarding nuget.exe. i just found it, the build.sh does not download nuget.exe compared to build.cmd which has been updated. thanks again for reporting.
could you post the log before your exception happens. this tells us what GPU you are trying to run on. it seems that Vulkan initialization fails due to old graphics driver. As @gsomix says, opengl must work on a broader set of hardware.
anyhow the exception should be fixed and tell exactly this

**Comment by jackfoxy** [comment]
@gsomix  that change seems to work, which is to say the window opens and displays  an object which I can move and resize.
But the command line shows a couple of errors: 
```
 0: ERROR: [GL:65537] GL error GL_INVALID_ENUM
 0: ERROR: [GL:65537] GL error GL_INVALID_VALUE
 0: ERROR: [GL:65538] GL error GL_INVALID_ENUM
```

The last error repeats.

**Comment by haraldsteinlechner** [comment]
the creation of the application should actually print some minimal information about your graphics card. For me it looks like this:
``` 0: initializing OpenGL runtime ..............................................
 0:   vendor:   "NVIDIA Corporation"
 0:   renderer: "GeForce GTX 1060 3GB/PCIe/SSE2"
 0:   version:  OpenGL 4.3.0 / GLSL 4.3
 0: initializing OpenGL runtime ...................................... 0.206 s
```
Similarly, the Vulkan Application prints even more detailled stuff.
Could you post this section in order to have better diagnosis here?

**Comment by krauthaufen** [comment]
reharding the nuget-problem: we could possibly fix that by using the new (v5) build script in the template, which also would not require mono to be installed on linux.

@jackfoxy Are you running the template on linux? over the last couple of months we didn't really take care of linux compat, but apart from some minor issues everything should be fine.

Glad to see people experimenting with aardvark,
cheers

**Comment by haraldsteinlechner** [comment]
EDIT: from @jackfoxy's log it looks like the problem occurs on windows (backslash paths). Yes @gsomix's templates would fix all those issues.

@krauthaufen i just checked linux support for multiple renderer/repository combinations. for example vulkan+media works just fine.

for this issue, please post your renderer stats as printed out during startup :)

**Comment by jackfoxy** [comment]
@haraldsteinlechner  here is the entire printed log up to window display. If I start manipulating the window contents more errors generate.
```
λ dotnet AardvarkTemplate.dll
 0: initializing aardvark ....................................................
 0:   System Information:
 0:     OSVersion: Microsoft Windows NT 10.0.18362.0
 0:     SystemArchitecture: 64-bit
 0:     Environment.Version: 4.0.30319.42000
 0:   Unpacking native dependencies .................................. 0.025 s
 0:   Loading plugins ................................................ 0.036 s
 0:   initializing PixImageDevil ..................................... 0.073 s
 0:   initializing ModModule .................................................
 0:     initializing mod system ...................................... 0.000 s
 0:   initializing ModModule ......................................... 0.000 s
 0:   initializing NewAg ............................................. 0.012 s
 0:   initializing Ag ................................................ 0.000 s
 0:   initializing SceneGraphCompletenessCheck ....................... 0.116 s
 0: initializing aardvark ............................................ 0.302 s
 0: ERROR: [GL:65537] GL error GL_INVALID_ENUM
 0: ERROR: [GL:65537] GL error GL_INVALID_VALUE
could not import function glBindTextures
could not import function glBindSamplers
could not import function glPolygonOffsetClampEXT
 0: initializing OpenGL runtime ..............................................
 0:   vendor:   "Intel"
 0:   renderer: "Intel(R) HD Graphics 4000"
 0:   version:  OpenGL 4.0.0 / GLSL 4.0
 0: initializing OpenGL runtime ...................................... 0.233 s
 0: ERROR: [GL:65537] GL error GL_INVALID_ENUM
 0: ERROR: [GL:65537] GL error GL_INVALID_VALUE
 0: ERROR: [GL:65538] GL error GL_INVALID_ENUM
 0: ERROR: [GL:65538] GL error GL_INVALID_ENUM
 0: ERROR: [GL:65538] GL error GL_INVALID_ENUM
 0: ERROR: [GL:65538] GL error GL_INVALID_ENUM
 0: ERROR: [GL:65538] GL error GL_INVALID_ENUM
 0: ERROR: [GL:65538] GL error GL_INVALID_ENUM
 0: [GL] RenderObjects: +1/-0 (1507ms)
 0: using optimized native program
```

**Comment by jackfoxy** [comment]
@krauthaufen  I use PowerShell 5 on Windows10

**Comment by haraldsteinlechner** [comment]
ok this might explain all problems:
 - something in build.cmd does not work when called from powershell compared to normal cmd.exe => nuget.exe not copied, we can check this out!
 - your graphics card does not seem to support vulkan. we should have better error reporting here.
 - although we have dozens of fallbacks for old hardware, something in our opengl implementation does not kick in. intel hd 4000 model is from 2011 i think. we did not regularly check on such hardware. i have the same one in my old laptop. in look at the problem there. 
 - quick guess: the problem might be related to multisampling enabled by default in the template. can you try using 1 instead of 8 in your Program.fs as shown here: https://github.com/aardvark-platform/template/blob/master/src/__PROJECT_NAME__/Rendering.fs#L15

one last thing: is by any chance another graphics card in your system which might be better (often laptops have dedicated+integrated combinations)?

PS: nice λ at the beginning of your command line :)

**Comment by krauthaufen** [comment]
hey, i just upgraded the template to v5 https://github.com/aardvark-platform/template/tree/v5

works on my machine, but would still be good if someone else could try that before merging it.

**Comment by jackfoxy** [comment]
@krauthaufen  v5 build and changing app to OpenGL worked for me.
 
Long story about my machine's lack of a real graphics card. Pretty sure my laptop has a better one. I'll check out things with it soon

**Comment by jackfoxy** [comment]
My laptop builds and runs both master and v5 branches, detects both available GPUs and runs well with the NVIDIA GPU selected
 
```
 0: Multiple GPUs detected (please select one)
 0:    0: NVIDIA Quadro P4200 with Max-Q Design
 0:    1: Intel Corporation Intel(R) UHD Graphics P630
```
